name: EndBlock
version: '${project.version}'
main: rama.endblock.EndBlock
api-version: 1.17
authors: [ Rama ]
description: Bloquea el mundo del End.
load: POSTWORLD
commands:
  endblock:
depend: [Multiverse-Core]
softdepend:
  - DragonSlayer
